VEK_STATUSES = ['Bringing Weird to the Masses','Vek Like Things','Chasing a Squirrel, Somewhere','Creeping Out Little Kids','Scaring Children','Getting Lost Somewhere','Still trying to find Geoff in WoW','Eating Pickles','His Rogue, doh, Rogue!','Getting on Burgener\'s Nerves','Trolling Meng']
VEK_DIRECTIONS = ['Go left, then right, next left, then right...','Check north, then south, then north again, followed by south...','Go up, then down, then back up, then down again..']
VEK_BODILY_FUNCTIONS = ['BURRRPPPPPP!','burp-Burrrrrrp~!','Braaap!','HIC!','HICCUP!','AAHHHCHOOOOO!']
VEK_TARGETS = ['Burgener', 'Meng']
SWEAR_FILTER = ['fuck','shit','ass','bitch','dick','cunt','damn','goddamn']